### ISSUE TITLE
Contribution guidlines

### ISSUE THREAD

**Issue by froger** [S3-working-group/s3-practical-guide#18]
Hello, 
First of all, thanks for your work, that's great resources. 
I feel a bit uncomfortable making proposals to this guide, could you clarify how can we contribute: 

* What is the guideline for contributions, you might choose one from https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors
* What is the governance regarding the evolution of S3? Could you clarify the process to integrate or update patterns? 

Thanks,
Hadrien Froger

**Comment by bboc** [comment]
Hi Hadrien,

thanks for offering contributions. Depending on what you have in mind, this repository may not be the right place, because I only use it for deploying the guide, but not for creating it. The content of the practical guide is being developed in various other tools by Lili David, James Priest and me, and once we agree on a change, I make the necessary updates to the repository. Therefore I don't monitor messages here on a regular basis.

So if you have suggestions for new patterns or significant updates to existing patterns please get in tough via the [S3 website's contact](https://sociocracy30.org/contact/) form. 

For typos, fixing sentences or technical stuff please add a ticket here.

I will also add a section to the README to clarify that.

**Comment by froger** [comment]
Thanks for the transparency @bboc, highly appreciate. 

Personally, I had in head some improvements, more on the page generation and the build system, for SEO, accessibility, etc. I know UI/UX designers that would be delighted to also propose some small updates, so I wanted to know what are the contribution guidelines in order to make proposals, and sponsor others to so. 
So your answer is perfect, I will plan some PR beginning 2021.


To be a force of proposition, I would suggest contribution guidelines like this one:
(shamelessly stolen from https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md)

```
# How to contribute?
I'm really glad you're reading this because we need volunteer developers to help this project.
If you haven't already, come find us in Mighty Network (https://community.sociocracy30.org/). We want you working on things you're excited about.

Here are some important resources:

* [S3 Intentional Commitment : https://sociocracy30.org/s3-intentional-commitment](https://sociocracy30.org/s3-intentional-commitment/)
* https://sociocracy30.org/
* [Our repositories](https://github.com/S3-working-group)

# Testing
Our time is limited, and we are working evolving S3 in the most efficient way. Please test thoughtfully the code you propose, and be sure the code can build and run seamlessly

# Submitting changes

**Significant updates: new patterns, new graphics, update patterns**
Lili David, James Priest and Bernhard Bockelbrink take care of the content written in the Sociocracy Practical Guide.
For suggestions, please contact us on [our website: https://sociocracy30.org/contact/](https://sociocracy30.org/contact/). 


**Minor changes: technical changes, typos, fixing sentences.**
Open an issue, minding testing for technical changes. On issues please document : 

* What is the current situation
* Why you are proposing changes
* Why your proposal is adding value to the current situation

```

Thanks!

**Comment by bboc** [comment]
@froger, thank you for your suggestions. James, Lili and I have met this morning and created a [page on sociocracy30.org](https://sociocracy30.org/ways-of-contributing-to-the-development-of-s3/) that explains how to submit suggestions. It is also linked in the [readme](https://github.com/S3-working-group/s3-practical-guide/blob/master/readme.md).

> Personally, I had in head some improvements, more on the page generation and the build system, for SEO, accessibility, etc. I know UI/UX designers that would be delighted to also propose some small updates, so I wanted to know what are the contribution guidelines in order to make proposals, and sponsor others to so.

That is great news. The two most important changes I am currently thinking about are:

- generating the pattern map as html for a responsive navigation overlay
- updating the build system so that we have more freedom to structure the guide in sections and chapters , and changing the build system of the guide so that we have more freedom for adding additional content besides the patterns, e.g. the Common Sense Framework

If you have any similar ideas, discussing them before you make a proposal would probably save us both some time

**Comment by froger** [comment]
Thanks @bboc that's amazing !

**Comment by bboc** [comment]
@froger FYI, I have released a new version of the build system, and a new version of the website with menu and keyboard shortcuts. 

see https://patterns.sociocracy30.org

I'm currently working on the html patterns map.
